import { db } from '@/lib/db'

async function main() {
  console.log('🌱 Seeding database...')

  // Clean existing data
  await db.inquiryItem.deleteMany()
  await db.inquiry.deleteMany()
  await db.testimonial.deleteMany()
  await db.contactMessage.deleteMany()
  await db.product.deleteMany()
  await db.category.deleteMany()

  console.log('✅ Cleared existing data')

  // =====================
  // CATEGORIES
  // =====================
  const categories = await db.category.createMany({
    data: [
      {
        name: 'AC Split',
        slug: 'ac-split',
        description: 'AC Split untuk kebutuhan residensial dan komersial. Tersedia berbagai kapasitas dari 0.5 PK hingga 5 PK dengan teknologi inverter terbaru.',
        image: '/images/categories/split-ac.png',
        sortOrder: 1,
      },
      {
        name: 'Kompresor',
        slug: 'kompresor',
        description: 'Kompresor AC berkualitas tinggi untuk semua merek. Tersedia kompresor rotary, scroll, dan reciprocating untuk berbagai tipe AC.',
        image: '/images/categories/kompresor.png',
        sortOrder: 2,
      },
      {
        name: 'Refrigerant',
        slug: 'refrigerant',
        description: 'Refrigerant / freon AC berkualitas standar internasional. Tersedia R32, R410A, R22, dan jenis lainnya dalam berbagai ukuran.',
        image: '/images/categories/refrigerant.png',
        sortOrder: 3,
      },
      {
        name: 'Spare Part AC',
        slug: 'spare-part-ac',
        description: 'Suku cadang AC lengkap untuk semua merek dan tipe. Kondensor, evaporator, fan motor, PCB, remote, dan komponen lainnya.',
        image: '/images/categories/sparepart.png',
        sortOrder: 4,
      },
      {
        name: 'Chiller & VRV/VRF',
        slug: 'chiller-vrv-vrf',
        description: 'Sistem pendingin sentral untuk gedung perkantoran, hotel, rumah sakit, dan pusat perbelanjaan. Chiller air-cooled dan water-cooled, serta sistem VRV/VRF.',
        image: '/images/categories/chiller.png',
        sortOrder: 5,
      },
      {
        name: 'Mesin Pendingin',
        slug: 'mesin-pendingin',
        description: 'Mesin pendingin industri untuk cold room, cold storage, freezer, dan aplikasi pendingin komersial lainnya.',
        image: '/images/categories/chiller.png',
        sortOrder: 6,
      },
    ],
  })

  console.log(`📦 Created ${categories.count} categories`)

  // Fetch categories for reference
  const catAcSplit = await db.category.findUnique({ where: { slug: 'ac-split' } })!
  const catKompresor = await db.category.findUnique({ where: { slug: 'kompresor' } })!
  const catRefrigerant = await db.category.findUnique({ where: { slug: 'refrigerant' } })!
  const catSparePart = await db.category.findUnique({ where: { slug: 'spare-part-ac' } })!
  const catChiller = await db.category.findUnique({ where: { slug: 'chiller-vrv-vrf' } })!
  const catMesinPendingin = await db.category.findUnique({ where: { slug: 'mesin-pendingin' } })!

  // =====================
  // PRODUCTS - AC Split
  // =====================
  const productsAcSplit = await db.product.createMany({
    data: [
      {
        name: 'Daikin FTKC25TVM4',
        slug: 'daikin-ftkc25tvm4',
        description: 'AC Split Daikin 1 PK Inverter dengan teknologi Streamer untuk udara bersih dan sejuk. Hemat energi hingga 30% dibandingkan AC non-inverter. Dilengkapi dengan Coanda Airflow untuk distribusi udara merata ke seluruh ruangan. Cocok untuk kamar tidur atau ruangan berukuran 10-15 m².',
        shortDesc: 'AC Split Daikin 1 PK Inverter - Hemat Energi',
        price: 5350000,
        originalPrice: 5800000,
        categoryId: catAcSplit.id,
        brand: 'Daikin',
        model: 'FTKC25TVM4',
        specifications: JSON.stringify({
          kapasitas: '1 PK (9.500 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'Inverter',
          daya_listrik: '730 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Streamer Technology', 'Coanda Airflow', 'Econo Mode', 'Intelligent Eye Sensor'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '770 x 285 x 205 mm',
          berat_indoor: '8 kg',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Panasonic CS-PU12VKJ',
        slug: 'panasonic-cs-pu12vkj',
        description: 'AC Split Panasonic 1.5 PK Standard dengan Nanoe-X Technology yang mampu menekan virus dan bakteri. Kapasitas pendinginan 12.000 BTU cocok untuk ruangan sedang hingga 18 m². Dilengkapi dengan Econavi Sensor untuk penghematan energi otomatis.',
        shortDesc: 'AC Split Panasonic 1.5 PK - Nanoe-X Technology',
        price: 4950000,
        originalPrice: 5300000,
        categoryId: catAcSplit.id,
        brand: 'Panasonic',
        model: 'CS-PU12VKJ',
        specifications: JSON.stringify({
          kapasitas: '1.5 PK (12.000 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'Standard (Non-Inverter)',
          daya_listrik: '1.080 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Nanoe-X Technology', 'Econavi Sensor', 'Blue Fin Condenser', 'Auto Restart'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '779 x 242 x 198 mm',
          berat_indoor: '9 kg',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Samsung AR10TYHQASINSE',
        slug: 'samsung-ar10tyhqasinse',
        description: 'AC Split Samsung 1 PK Digital Inverter dengan Triple Protector Plus untuk daya tahan maksimal. Teknologi Wind-Free™ menghadirkan kesejukan tanpa angin langsung. Cerdas dan hemat energi dengan konsumsi listrik rendah.',
        shortDesc: 'AC Split Samsung 1 PK Inverter - Wind-Free Technology',
        price: 4650000,
        originalPrice: 5100000,
        categoryId: catAcSplit.id,
        brand: 'Samsung',
        model: 'AR10TYHQASINSE',
        specifications: JSON.stringify({
          kapasitas: '1 PK (9.200 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'Digital Inverter',
          daya_listrik: '680 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Wind-Free™ Cooling', 'Triple Protector Plus', 'SmartThings Compatible', 'Fast Cooling Mode'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '820 x 315 x 205 mm',
          berat_indoor: '9.5 kg',
        }),
        inStock: true,
        isFeatured: true,
        isNew: true,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'LG T06EV4',
        slug: 'lg-t06ev4',
        description: 'AC Split LG 0.5 PK Standard dengan Dual Inverter Compressor untuk pendinginan cepat dan hemat energi. Kapasitas 6.500 BTU ideal untuk kamar kecil 6-9 m². Dilengkapi LG Smart ThinQ untuk kontrol via smartphone.',
        shortDesc: 'AC Split LG 0.5 PK - Dual Inverter',
        price: 3250000,
        originalPrice: 3500000,
        categoryId: catAcSplit.id,
        brand: 'LG',
        model: 'T06EV4',
        specifications: JSON.stringify({
          kapasitas: '0.5 PK (6.500 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'Dual Inverter',
          daya_listrik: '450 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Dual Inverter Compressor', 'LG ThinQ Smart Control', 'Ocean Black Fin', 'Low Refrigerant Detection'],
          garansi: '10 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '770 x 245 x 200 mm',
          berat_indoor: '8 kg',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Gree GPK-12TPL',
        slug: 'gree-gpk-12tpl',
        description: 'AC Split Gree 1.5 PK dengan teknologi G10 Inverter untuk efisiensi energi optimal. Dilengkapi dengan Cold Plasma Technology yang menjaga kualitas udara dalam ruangan. Desain elegan cocok untuk rumah dan kantor.',
        shortDesc: 'AC Split Gree 1.5 PK Inverter - Cold Plasma',
        price: 4200000,
        originalPrice: 4600000,
        categoryId: catAcSplit.id,
        brand: 'Gree',
        model: 'GPK-12TPL',
        specifications: JSON.stringify({
          kapasitas: '1.5 PK (12.000 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'G10 Inverter',
          daya_listrik: '950 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Cold Plasma Technology', 'Intelligent Defrosting', 'Auto Clean', 'Sleep Mode'],
          garansi: '5 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '860 x 280 x 200 mm',
          berat_indoor: '10 kg',
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Daikin FTKJ35TV16',
        slug: 'daikin-ftkj35tv16',
        description: 'AC Split Daikin 1.5 PK Inverter dengan Stator Core Technology untuk efisiensi tinggi. Kapasitas 13.400 BTU cocok untuk ruangan hingga 20 m². Dilengkapi filter titanium apatite untuk menangkap partikel halus dan bakteri.',
        shortDesc: 'AC Split Daikin 1.5 PK Inverter Premium',
        price: 6750000,
        originalPrice: 7200000,
        categoryId: catAcSplit.id,
        brand: 'Daikin',
        model: 'FTKJ35TV16',
        specifications: JSON.stringify({
          kapasitas: '1.5 PK (13.400 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'Inverter',
          daya_listrik: '1.080 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Stator Core Technology', 'Titanium Apatite Filter', 'Coanda Airflow', 'Patrol Sensor'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '950 x 298 x 220 mm',
          berat_indoor: '11 kg',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Panasonic CS-XU13XKJ',
        slug: 'panasonic-cs-xu13xkj',
        description: 'AC Split Panasonic 2 PK Inverter Econavi dengan kapasitas 19.000 BTU untuk ruangan besar hingga 26 m². Dilengkapi dengan AI sensor yang mendeteksi keberadaan manusia dan menyesuaikan suhu otomatis. Sistem Nanoe-G murnikan udara dari partikel PM2.5.',
        shortDesc: 'AC Split Panasonic 2 PK Inverter AI Sensor',
        price: 8200000,
        originalPrice: 8900000,
        categoryId: catAcSplit.id,
        brand: 'Panasonic',
        model: 'CS-XU13XKJ',
        specifications: JSON.stringify({
          kapasitas: '2 PK (19.000 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'Inverter + Econavi AI',
          daya_listrik: '1.650 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Econavi AI Sensor', 'Nanoe-G', 'Blue Fin Condenser', 'Mild Dry Cooling'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '1.079 x 320 x 238 mm',
          berat_indoor: '14 kg',
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Mitsubishi MSY-GL10NA',
        slug: 'mitsubishi-msy-gl10na',
        description: 'AC Split Mitsubishi Electric 1 PK dengan desain compact dan efisiensi energi tinggi. Menggunakan kompresor inverter buatan Jepang yang tahan lama. Cocok untuk ruangan 10-15 m² dengan operasi senyap hanya 19 dB.',
        shortDesc: 'AC Split Mitsubishi 1 PK - Super Quiet 19dB',
        price: 5900000,
        originalPrice: 6300000,
        categoryId: catAcSplit.id,
        brand: 'Mitsubishi',
        model: 'MSY-GL10NA',
        specifications: JSON.stringify({
          kapasitas: '1 PK (10.000 BTU/h)',
          tipe: 'Split Wall Mounted',
          teknologi: 'Inverter',
          daya_listrik: '750 Watt',
          tegangan: '220V / 50Hz',
          refrigerant: 'R32',
          fitur: ['Super Quiet 19dB', 'Anti-Bacterial Filter', 'Auto Diagnostics', 'Self-Clean Function'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
          dimensi_indoor: '798 x 295 x 215 mm',
          berat_indoor: '9 kg',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
    ],
  })

  console.log(`📦 Created ${productsAcSplit.count} AC Split products`)

  // =====================
  // PRODUCTS - Kompresor
  // =====================
  const productsKompresor = await db.product.createMany({
    data: [
      {
        name: 'Kompresor Daikin Rotary 1 PK R32',
        slug: 'kompresor-daikin-rotary-1pk-r32',
        description: 'Kompresor rotary Daikin asli untuk AC split 1 PK. Kompatibel dengan refrigerant R32. Kualitas OEM dengan performa optimal dan daya tahan tinggi. Cocok sebagai pengganti kompresor rusak pada unit Daikin seri FTKC.',
        shortDesc: 'Kompresor Rotary Daikin 1 PK - Original OEM',
        price: 1850000,
        originalPrice: 2100000,
        categoryId: catKompresor.id,
        brand: 'Daikin',
        model: 'TZS220',
        specifications: JSON.stringify({
          tipe: 'Rotary',
          kapasitas: '1 PK',
          refrigerant: 'R32',
          tegangan: '220V / 50Hz',
          daya_listrik: '730 Watt',
          frekuensi: '50Hz',
          berat: '5.2 kg',
          garansi: '1 Tahun',
          kompatibel_merek: ['Daikin FTKC Series', 'Daikin FTKJ Series'],
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kompresor Panasonic Rotary 1.5 PK R410A',
        slug: 'kompresor-panasonic-rotory-1.5pk-r410a',
        description: 'Kompresor rotary Panasonic untuk AC split 1.5 PK. Dirancang khusus untuk sistem R410A dengan efisiensi pendinginan tinggi. Kualitas original Panasonic Japan.',
        shortDesc: 'Kompresor Rotary Panasonic 1.5 PK R410A',
        price: 2150000,
        originalPrice: 2400000,
        categoryId: catKompresor.id,
        brand: 'Panasonic',
        model: '2PS164D5CA01',
        specifications: JSON.stringify({
          tipe: 'Rotary',
          kapasitas: '1.5 PK',
          refrigerant: 'R410A',
          tegangan: '220V / 50Hz',
          daya_listrik: '1.080 Watt',
          frekuensi: '50Hz',
          berat: '6.8 kg',
          garansi: '1 Tahun',
          kompatibel_merek: ['Panasonic CS/CU Series'],
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kompresor Samsung Twin Rotary 1 PK R32',
        slug: 'kompresor-samsung-twin-rotary-1pk-r32',
        description: 'Kompresor Twin Rotary Samsung Digital Inverter untuk AC 1 PK. Teknologi twin rotary memberikan efisiensi lebih tinggi dan getaran lebih rendah. Kompatibel dengan refrigerant R32.',
        shortDesc: 'Kompresor Twin Rotary Samsung 1 PK Inverter',
        price: 1750000,
        originalPrice: 1950000,
        categoryId: catKompresor.id,
        brand: 'Samsung',
        model: 'STK-3102C',
        specifications: JSON.stringify({
          tipe: 'Twin Rotary Inverter',
          kapasitas: '1 PK',
          refrigerant: 'R32',
          tegangan: '220V / 50Hz',
          daya_listrik: '680 Watt',
          frekuensi: '50Hz',
          berat: '5.5 kg',
          garansi: '1 Tahun',
          kompatibel_merek: ['Samsung AR Series'],
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kompresor Gree Scroll 2 PK R410A',
        slug: 'kompresor-gree-scroll-2pk-r410a',
        description: 'Kompresor scroll Gree untuk AC split 2 PK. Tipe scroll memberikan performa pendinginan stabil dan efisien untuk kapasitas besar. Kualitas original Gree China dengan sertifikasi internasional.',
        shortDesc: 'Kompresor Scroll Gree 2 PK',
        price: 2650000,
        originalPrice: 2900000,
        categoryId: catKompresor.id,
        brand: 'Gree',
        model: 'GZ-090T1',
        specifications: JSON.stringify({
          tipe: 'Scroll',
          kapasitas: '2 PK',
          refrigerant: 'R410A',
          tegangan: '220V / 50Hz',
          daya_listrik: '1.650 Watt',
          frekuensi: '50Hz',
          berat: '9.5 kg',
          garansi: '1 Tahun',
          kompatibel_merek: ['Gree GPK/GPC Series'],
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kompresor LG Dual Inverter 1.5 PK R32',
        slug: 'kompresor-lg-dual-inverter-1.5pk-r32',
        description: 'Kompresor LG Dual Inverter untuk AC split 1.5 PK. Teknologi dual inverter mengurangi konsumsi listrik hingga 60% dibanding kompresor konvensional. Tahan lama dengan balok motor luas.',
        shortDesc: 'Kompresor LG Dual Inverter 1.5 PK R32',
        price: 2300000,
        originalPrice: 2550000,
        categoryId: catKompresor.id,
        brand: 'LG',
        model: 'LS55673601',
        specifications: JSON.stringify({
          tipe: 'Dual Rotary Inverter',
          kapasitas: '1.5 PK',
          refrigerant: 'R32',
          tegangan: '220V / 50Hz',
          daya_listrik: '950 Watt',
          frekuensi: '50Hz',
          berat: '7.0 kg',
          garansi: '1 Tahun',
          kompatibel_merek: ['LG T-Series Dual Inverter'],
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kompresor Copeland Scroll 5 HP R404A',
        slug: 'kompresor-copeland-scroll-5hp-r404a',
        description: 'Kompresor scroll Copeland (Emerson) untuk sistem chiller dan cold storage kapasitas 5 HP. Kualitas industri berstandar internasional. Tahan terhadap beban kerja berat dan operasi kontinu.',
        shortDesc: 'Kompresor Scroll Copeland 5 HP Industrial',
        price: 18500000,
        originalPrice: 20000000,
        categoryId: catKompresor.id,
        brand: 'Copeland',
        model: 'ZR72KCE-TFD',
        specifications: JSON.stringify({
          tipe: 'Scroll',
          kapasitas: '5 HP (15.000 BTU/h)',
          refrigerant: 'R404A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '3.750 Watt',
          frekuensi: '50Hz',
          berat: '32 kg',
          garansi: '1 Tahun',
          aplikasi: ['Cold Storage', 'Chiller', 'Freezer'],
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kompresor Danfoss Reciprocating 3 HP R22',
        slug: 'kompresor-danfoss-reciprocating-3hp-r22',
        description: 'Kompresor reciprocating Danfoss untuk sistem pendingin komersial. Kapasitas 3 HP cocok untuk cold room dan freezer. Desain tahan lama dengan pelumas khusus untuk R22.',
        shortDesc: 'Kompresor Reciprocating Danfoss 3 HP R22',
        price: 12500000,
        originalPrice: 14000000,
        categoryId: catKompresor.id,
        brand: 'Danfoss',
        model: 'SC18G',
        specifications: JSON.stringify({
          tipe: 'Reciprocating',
          kapasitas: '3 HP',
          refrigerant: 'R22',
          tegangan: '220V / 50Hz',
          daya_listrik: '2.250 Watt',
          frekuensi: '50Hz',
          berat: '25 kg',
          garansi: '1 Tahun',
          aplikasi: ['Cold Room', 'Freezer', 'Display Chiller'],
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kompresor Toshiba Rotary 2 PK R410A',
        slug: 'kompresor-toshiba-rotary-2pk-r410a',
        description: 'Kompresor rotary Toshiba untuk AC split 2 PK. Performa tinggi dengan tingkat kebisingan rendah. Kualitas original Toshiba Japan dengan desain compact.',
        shortDesc: 'Kompresor Rotary Toshiba 2 PK R410A',
        price: 2450000,
        originalPrice: 2700000,
        categoryId: catKompresor.id,
        brand: 'Toshiba',
        model: 'GL104MBYK',
        specifications: JSON.stringify({
          tipe: 'Rotary',
          kapasitas: '2 PK',
          refrigerant: 'R410A',
          tegangan: '220V / 50Hz',
          daya_listrik: '1.650 Watt',
          frekuensi: '50Hz',
          berat: '8.5 kg',
          garansi: '1 Tahun',
          kompatibel_merek: ['Toshiba RAS Series'],
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
    ],
  })

  console.log(`📦 Created ${productsKompresor.count} Kompresor products`)

  // =====================
  // PRODUCTS - Refrigerant
  // =====================
  const productsRefrigerant = await db.product.createMany({
    data: [
      {
        name: 'Freon R32 Daikin - 1 Kg',
        slug: 'freon-r32-daikin-1kg',
        description: 'Refrigerant R32 Daikin berkualitas tinggi. Freon generasi terbaru yang lebih ramah lingkungan dengan GWP lebih rendah dari R410A. Kapasitas pendinginan lebih efisien per kilogram dibanding freon konvensional.',
        shortDesc: 'Freon R32 Daikin - Ramah Lingkungan',
        price: 185000,
        originalPrice: 220000,
        categoryId: catRefrigerant.id,
        brand: 'Daikin',
        model: 'R32-1KG',
        specifications: JSON.stringify({
          jenis: 'R32 (Difluoromethane)',
          berat_bersih: '1 kg',
          kemasan: 'Kaleng',
          GWP: '675',
          ODP: '0',
          titik_didih: '-51.7°C',
          tekanan_kerja: '25.6 bar (50°C)',
          kompatibel: ['AC Split Inverter', 'AC Split Standard'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'kaleng',
      },
      {
        name: 'Freon R410A - 10 Kg',
        slug: 'freon-r410a-10kg',
        description: 'Refrigerant R410A kemasan 10 kg untuk pengisian ulang AC skala besar. Campuran zeotropik 50% R32 dan 50% R125. Cocok untuk AC central dan VRV/VRF system.',
        shortDesc: 'Freon R410A Kemasan 10 Kg - Hemat',
        price: 1650000,
        originalPrice: 1800000,
        categoryId: catRefrigerant.id,
        brand: 'Chemours',
        model: 'R410A-10KG',
        specifications: JSON.stringify({
          jenis: 'R410A (50% R32 / 50% R125)',
          berat_bersih: '10 kg',
          kemasan: 'Tabung Besi',
          GWP: '2088',
          ODP: '0',
          titik_didih: '-51.5°C',
          tekanan_kerja: '27.5 bar (50°C)',
          kompatibel: ['AC Split', 'VRV/VRF System', 'Chiller'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'tabung',
      },
      {
        name: 'Freon R22 - 1 Kg',
        slug: 'freon-r22-1kg',
        description: 'Refrigerant R22 (Chlorodifluoromethane) untuk AC lama dan sistem pendingin konvensional. Meskipun produksi sudah dibatasi, R22 masih banyak digunakan pada AC yang sudah terpasang.',
        shortDesc: 'Freon R22 - 1 Kg Kaleng',
        price: 125000,
        originalPrice: 150000,
        categoryId: catRefrigerant.id,
        brand: 'Generic',
        model: 'R22-1KG',
        specifications: JSON.stringify({
          jenis: 'R22 (Chlorodifluoromethane)',
          berat_bersih: '1 kg',
          kemasan: 'Kaleng',
          GWP: '1810',
          ODP: '0.055',
          titik_didih: '-40.8°C',
          tekanan_kerja: '19.3 bar (50°C)',
          kompatibel: ['AC Split Lawas', 'AC Window', 'Kulkas', 'Cold Storage'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'kaleng',
      },
      {
        name: 'Freon R134a - 12 Kg',
        slug: 'freon-r134a-12kg',
        description: 'Refrigerant R134a kemasan 12 kg untuk sistem pendingin otomotif dan komersial. Banyak digunakan pada AC mobil, chiller kecil, dan showcase pendingin. Aman untuk lingkungan dengan ODP nol.',
        shortDesc: 'Freon R134a 12 Kg - AC Mobil & Komersial',
        price: 1400000,
        originalPrice: 1600000,
        categoryId: catRefrigerant.id,
        brand: 'Honeywell',
        model: 'R134a-12KG',
        specifications: JSON.stringify({
          jenis: 'R134a (Tetrafluoroethane)',
          berat_bersih: '12 kg',
          kemasan: 'Tabung Besi',
          GWP: '1430',
          ODP: '0',
          titik_didih: '-26.1°C',
          tekanan_kerja: '13.2 bar (50°C)',
          kompatibel: ['AC Mobil', 'Chiller Kecil', 'Showcase', 'Vending Machine'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'tabung',
      },
      {
        name: 'Freon R404A - 10 Kg',
        slug: 'freon-r404a-10kg',
        description: 'Refrigerant R404A kemasan 10 kg untuk aplikasi pendingin komersial dan industri. Sangat cocok untuk cold storage, freezer, dan sistem refrigerasi suhu rendah. Campuran HFC dengan performa pendinginan excellent.',
        shortDesc: 'Freon R404A 10 Kg - Cold Storage & Freezer',
        price: 2200000,
        originalPrice: 2500000,
        categoryId: catRefrigerant.id,
        brand: 'Chemours',
        model: 'R404A-10KG',
        specifications: JSON.stringify({
          jenis: 'R404A (Blend HFC)',
          berat_bersih: '10 kg',
          kemasan: 'Tabung Besi',
          GWP: '3922',
          ODP: '0',
          titik_didih: '-46.5°C',
          tekanan_kerja: '24.2 bar (50°C)',
          kompatibel: ['Cold Storage', 'Freezer', 'Blast Chiller', 'Ice Machine'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'tabung',
      },
      {
        name: 'Freon R32 - 10 Kg',
        slug: 'freon-r32-10kg',
        description: 'Refrigerant R32 kemasan ekonomis 10 kg untuk teknisi AC profesional. Pengisian ulang berulang kali lebih hemat dengan kemasan besar. Freon R32 merupakan pilihan ramah lingkungan untuk AC modern.',
        shortDesc: 'Freon R32 10 Kg - Kemasan Ekonomis',
        price: 1550000,
        originalPrice: 1700000,
        categoryId: catRefrigerant.id,
        brand: 'Daikin',
        model: 'R32-10KG',
        specifications: JSON.stringify({
          jenis: 'R32 (Difluoromethane)',
          berat_bersih: '10 kg',
          kemasan: 'Tabung Besi',
          GWP: '675',
          ODP: '0',
          titik_didih: '-51.7°C',
          tekanan_kerja: '25.6 bar (50°C)',
          kompatibel: ['AC Split Inverter', 'AC Split Standard'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'tabung',
      },
      {
        name: 'Freon R290 Propan - 5 Kg',
        slug: 'freon-r290-propan-5kg',
        description: 'Refrigerant R290 (Propan) kemasan 5 kg untuk sistem pendingin ramah lingkungan. GWP sangat rendah (3) menjadikannya pilihan masa depan. Cocok untuk showcase, chiller kecil, dan heat pump.',
        shortDesc: 'Freon R290 Propan 5 Kg - Ultra Green',
        price: 950000,
        originalPrice: null,
        categoryId: catRefrigerant.id,
        brand: 'Linde',
        model: 'R290-5KG',
        specifications: JSON.stringify({
          jenis: 'R290 (Propan)',
          berat_bersih: '5 kg',
          kemasan: 'Tabung Besi',
          GWP: '3',
          ODP: '0',
          titik_didih: '-42.1°C',
          tekanan_kerja: '17.1 bar (50°C)',
          kompatibel: ['Showcase', 'Chiller Kecil', 'Heat Pump', 'Vending Machine'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'tabung',
      },
      {
        name: 'Freon R410A - 1 Kg',
        slug: 'freon-r410a-1kg',
        description: 'Refrigerant R410A kemasan 1 kg untuk pengisian AC split satuan. Praktis dan mudah dibawa untuk pekerjaan service AC di lokasi pelanggan.',
        shortDesc: 'Freon R410A 1 Kg - Praktis',
        price: 195000,
        originalPrice: 230000,
        categoryId: catRefrigerant.id,
        brand: 'Generic',
        model: 'R410A-1KG',
        specifications: JSON.stringify({
          jenis: 'R410A (50% R32 / 50% R125)',
          berat_bersih: '1 kg',
          kemasan: 'Kaleng',
          GWP: '2088',
          ODP: '0',
          titik_didih: '-51.5°C',
          tekanan_kerja: '27.5 bar (50°C)',
          kompatibel: ['AC Split', 'VRV/VRF System'],
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'kaleng',
      },
    ],
  })

  console.log(`📦 Created ${productsRefrigerant.count} Refrigerant products`)

  // =====================
  // PRODUCTS - Spare Part AC
  // =====================
  const productsSparePart = await db.product.createMany({
    data: [
      {
        name: 'Kondensor AC Split Daikin 1 PK',
        slug: 'kondensor-ac-split-daikin-1pk',
        description: 'Kondensor (coil luar) AC Split Daikin 1 PK original. Diproduksi dari material aluminium dan tembaga berkualitas tinggi. Cocok untuk penggantian kondensor yang bocor atau rusak.',
        shortDesc: 'Kondensor AC Daikin 1 PK - OEM',
        price: 1450000,
        originalPrice: 1700000,
        categoryId: catSparePart.id,
        brand: 'Daikin',
        model: 'KND-DK-1PK',
        specifications: JSON.stringify({
          tipe: 'Kondensor Outdoor',
          kapasitas: '1 PK',
          material: 'Aluminium Fin + Tembaga Tube',
          dimensi: '780 x 260 x 200 mm',
          berat: '4.5 kg',
          kompatibel: ['Daikin 1 PK FTKC Series'],
          garansi: '6 Bulan',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Fan Motor Indoor AC Universal 1-1.5 PK',
        slug: 'fan-motor-indoor-ac-universal-1-1.5pk',
        description: 'Fan motor indoor universal untuk AC split 1 hingga 1.5 PK. Bisa digunakan untuk berbagai merek AC. Kualitas bagus dengan bantalan bola (ball bearing) yang tahan lama.',
        shortDesc: 'Fan Motor Indoor Universal 1-1.5 PK',
        price: 285000,
        originalPrice: 320000,
        categoryId: catSparePart.id,
        brand: 'Universal',
        model: 'FM-IND-15',
        specifications: JSON.stringify({
          tipe: 'Fan Motor Indoor (Cross Flow)',
          kapasitas: '1 - 1.5 PK',
          tegangan: '220V / 50Hz',
          RPM: '1.200',
          berat: '1.2 kg',
          kompatibel: ['Daikin', 'Panasonic', 'Samsung', 'LG', 'Gree'],
          garansi: '3 Bulan',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'PCB Board AC Daikin 1 PK Inverter',
        slug: 'pcb-board-ac-daikin-1pk-inverter',
        description: 'PCB board kontrol AC Daikin 1 PK Inverter. Original spare part untuk mengganti PCB yang rusak akibat lonjakan listrik atau kerusakan komponen elektronik.',
        shortDesc: 'PCB Board Daikin 1 PK Inverter - Original',
        price: 1250000,
        originalPrice: 1500000,
        categoryId: catSparePart.id,
        brand: 'Daikin',
        model: 'A2193-0262',
        specifications: JSON.stringify({
          tipe: 'PCB Kontrol (Main Board)',
          kompatibel_model: ['FTKC25TVM4', 'FTKC25TVM4S', 'FTKC20TVM4'],
          tegangan_input: '220V AC',
          berat: '0.5 kg',
          kelengkapan: ['PCB Board', 'Connector Set', 'Manual'],
          garansi: '6 Bulan',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Remote AC Universal - All Brand',
        slug: 'remote-ac-universal-all-brand',
        description: 'Remote AC universal yang kompatibel dengan hampir semua merek AC. Dilengkapi layar LCD, timer, dan mode swing. Mudah diprogram dengan fitur auto-search kode.',
        shortDesc: 'Remote AC Universal - Semua Merek',
        price: 85000,
        originalPrice: 120000,
        categoryId: catSparePart.id,
        brand: 'Universal',
        model: 'RM-UNI-001',
        specifications: JSON.stringify({
          tipe: 'Remote Universal AC',
          kompatibel: ['Daikin', 'Panasonic', 'Samsung', 'LG', 'Gree', 'Toshiba', 'Mitsubishi', 'Sharp', 'Polytron'],
          daya: '2x AAA Battery',
          jarak: 'Hingga 8 meter',
          fitur: ['LCD Display', 'Timer On/Off', 'Swing', 'Auto Search', 'Sleep Mode'],
          garansi: '1 Bulan',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Kapasitor AC 35µF 450VAC',
        slug: 'kapasitor-ac-35uf-450vac',
        description: 'Kapasitor running AC split 35µF 450VAC. Umumnya digunakan pada AC 1.5 PK. Kualitas bagus dengan tahanan terhadap suhu tinggi. Pengganti kapasitor yang menggelembung atau lemah.',
        shortDesc: 'Kapasitor AC 35µF 450VAC - 1.5 PK',
        price: 75000,
        originalPrice: 95000,
        categoryId: catSparePart.id,
        brand: 'Schneider',
        model: 'CAP-35-450',
        specifications: JSON.stringify({
          tipe: 'Running Capacitor',
          kapasitansi: '35 µF',
          tegangan: '450 VAC',
          frekuensi: '50/60 Hz',
          untuk_pk: '1.5 PK',
          dimensi: '45 x 35 x 80 mm',
          suhu_operasi: '-25°C ~ +70°C',
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Filter Udara AC Split Universal (Set 2pcs)',
        slug: 'filter-udara-ac-split-universal-set',
        description: 'Filter udara AC split universal berbahan mesh premium. Set berisi 2 pcs (filter jaring dan filter karbon aktif). Membantu menjaga kebersihan udara dan melindungi evaporator dari debu.',
        shortDesc: 'Filter Udara AC Universal - Set 2 Pcs',
        price: 45000,
        originalPrice: 65000,
        categoryId: catSparePart.id,
        brand: 'Universal',
        model: 'FLT-UNI-SET',
        specifications: JSON.stringify({
          tipe: 'Air Filter Set',
          isi: '2 pcs (Mesh + Carbon)',
          ukuran: 'Dipotong sesuai unit',
          material: 'Mesh PP + Activated Carbon',
          daya_tahan: '3-6 bulan pemakaian',
          kompatibel: ['Semua AC Split Wall Mounted'],
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'set',
      },
      {
        name: 'Evaporator AC Split 1.5 PK Universal',
        slug: 'evaporator-ac-split-1.5pk-universal',
        description: 'Evaporator (coil indoor) AC split 1.5 PK universal. Kualitas bagus dengan fin aluminium dan tube tembaga. Cocok untuk penggantian evaporator yang bocor atau tersumbat.',
        shortDesc: 'Evaporator AC Split 1.5 PK Universal',
        price: 1350000,
        originalPrice: 1600000,
        categoryId: catSparePart.id,
        brand: 'Universal',
        model: 'EVP-UNI-15PK',
        specifications: JSON.stringify({
          tipe: 'Evaporator Indoor',
          kapasitas: '1.5 PK',
          material: 'Aluminium Fin + Tembaga Tube',
          dimensi: '700 x 250 x 30 mm',
          berat: '2.8 kg',
          kompatibel: ['AC Split 1.5 PK Universal'],
          garansi: '6 Bulan',
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Isolasi Pipa AC 3/4 + 1/4 (1 Roll 15m)',
        slug: 'isolasi-pipa-ac-3-4-1-4-roll-15m',
        description: 'Isolasi pipa AC elastomer kualitas tinggi untuk pipa pendingin 3/4 dan 1/4 inci. Tahan terhadap kelembaban dan UV. Panjang 15 meter per roll, cukup untuk 2-3 unit AC.',
        shortDesc: 'Isolasi Pipa AC Elastomer 15m',
        price: 125000,
        originalPrice: 150000,
        categoryId: catSparePart.id,
        brand: 'Armaflex',
        model: 'ISO-AC-15M',
        specifications: JSON.stringify({
          tipe: 'Insulasi Pipa Elastomer',
          ukuran_pipa: '3/4" + 1/4"',
          panjang: '15 meter / roll',
          tebal: '9 mm',
          ketebalan_isolasi: 'R-Value 2.8',
          suhu_kerja: '-40°C ~ +105°C',
          warna: 'Hitam',
          sertifikasi: 'SNI',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'roll',
      },
    ],
  })

  console.log(`📦 Created ${productsSparePart.count} Spare Part products`)

  // =====================
  // PRODUCTS - Chiller & VRV/VRF
  // =====================
  const productsChiller = await db.product.createMany({
    data: [
      {
        name: 'Daikin VRV IV+ 5 PK (Indoor Unit + Outdoor)',
        slug: 'daikin-vrv-iv-plus-5pk',
        description: 'Sistem VRV Daikin IV+ kapasitas 5 HP untuk gedung perkantoran dan komersial. Mendukung hingga 9 indoor unit dengan konfigurasi fleksibel. Efisiensi COP hingga 5.15 untuk penghematan energi optimal.',
        shortDesc: 'Daikin VRV IV+ 5 HP - Sistem Central AC',
        price: 85000000,
        originalPrice: 95000000,
        categoryId: catChiller.id,
        brand: 'Daikin',
        model: 'RXYQ5TAYJ',
        specifications: JSON.stringify({
          tipe: 'VRV IV+ (Outdoor Unit)',
          kapasitas: '5 HP (48.000 BTU/h)',
          refrigerant: 'R410A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '4.200 Watt',
          COP: '5.15',
          max_indoor_unit: '9 unit',
          jarak_pipa_maks: '50 meter (level sama)',
          fitur: ['Intelligent Touch Controller', 'Weekly Timer', 'High Pressure Lift', 'Night Purge Operation'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'set',
      },
      {
        name: 'Mitsubishi VRF City Multi 8 PK',
        slug: 'mitsubishi-vrf-city-multi-8pk',
        description: 'Sistem VRF Mitsubishi Electric City Multi kapasitas 8 HP untuk gedung menengah. Mampu melayani hingga 16 indoor unit. Teknologi inverter dual-kompressor untuk efisiensi pada beban parsial.',
        shortDesc: 'Mitsubishi VRF City Multi 8 HP',
        price: 145000000,
        originalPrice: 160000000,
        categoryId: catChiller.id,
        brand: 'Mitsubishi',
        model: 'PUHY-P168YKA',
        specifications: JSON.stringify({
          tipe: 'VRF (Outdoor Unit)',
          kapasitas: '8 HP (76.000 BTU/h)',
          refrigerant: 'R410A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '6.800 Watt',
          COP: '4.85',
          max_indoor_unit: '16 unit',
          jarak_pipa_maks: '75 meter (level sama)',
          fitur: ['Dual Compressor', 'Auto Addressing', 'Lossnay Compatible', 'Touch Controller'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'set',
      },
      {
        name: 'Chiller Air-Cooled Daikin 20 PK',
        slug: 'chiller-air-cooled-daikin-20pk',
        description: 'Chiller air-cooled Daikin kapasitas 20 HP untuk sistem pendingin sentral gedung. Menggunakan kompresor scroll dan kipas aksial. Efisiensi tinggi dengan kontrol mikroprosesor canggih.',
        shortDesc: 'Chiller Air-Cooled Daikin 20 HP',
        price: 285000000,
        originalPrice: 320000000,
        categoryId: catChiller.id,
        brand: 'Daikin',
        model: 'EWAD200J-XR',
        specifications: JSON.stringify({
          tipe: 'Air-Cooled Chiller',
          kapasitas_pendinginan: '20 HP (190.000 BTU/h / 55 kW)',
          refrigerant: 'R410A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '17.500 Watt',
          COP: '3.14',
          suhu_air_keluar: '7°C',
          aliran_air: '9.5 m³/h',
          fitur: ['Microprocessor Control', 'Anti-Freeze Protection', 'Soft Starter', 'BMS Compatible'],
          garansi: '2 Tahun',
        }),
        inStock: true,
        isFeatured: true,
        isNew: true,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Panasonic VRF ECOi 10 PK',
        slug: 'panasonic-vrf-ecoi-10pk',
        description: 'Sistem VRF Panasonic ECOi kapasitas 10 HP untuk gedung komersial. Mampu melayani hingga 20 indoor unit. Dilengkapi sensor CO2 dan kontrol zona individual untuk kenyamanan optimal.',
        shortDesc: 'Panasonic VRF ECOi 10 HP - Smart Building',
        price: 175000000,
        originalPrice: 195000000,
        categoryId: catChiller.id,
        brand: 'Panasonic',
        model: 'PUH-P240YKA',
        specifications: JSON.stringify({
          tipe: 'VRF (Outdoor Unit)',
          kapasitas: '10 HP (96.000 BTU/h)',
          refrigerant: 'R410A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '8.200 Watt',
          COP: '4.70',
          max_indoor_unit: '20 unit',
          jarak_pipa_maks: '100 meter',
          fitur: ['CO2 Sensor', 'Zone Control', 'Econavi AI', 'Cloud Management'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'set',
      },
      {
        name: 'Chiller Water-Cooled McQuay 30 PK',
        slug: 'chiller-water-cooled-mcquay-30pk',
        description: 'Chiller water-cooled McQuay (Daikin Applied) kapasitas 30 HP untuk pusat perbelanjaan dan hotel. Efisiensi tinggi dengan COP 5.2. Membutuhkan cooling tower terpisah.',
        shortDesc: 'Chiller Water-Cooled McQuay 30 HP',
        price: 450000000,
        originalPrice: 500000000,
        categoryId: catChiller.id,
        brand: 'McQuay',
        model: 'AGZ-030',
        specifications: JSON.stringify({
          tipe: 'Water-Cooled Scroll Chiller',
          kapasitas_pendinginan: '30 HP (285.000 BTU/h / 83 kW)',
          refrigerant: 'R134a',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '16.000 Watt',
          COP: '5.2',
          suhu_air_chilled: '7°C',
          aliran_air: '14.3 m³/h',
          fitur: ['BMS Modbus RTU', 'Dual Compressor', 'VFD Compatible', 'Remote Monitoring'],
          garansi: '2 Tahun',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Daikin VRV IV+ 10 PK',
        slug: 'daikin-vrv-iv-plus-10pk',
        description: 'Sistem VRV Daikin IV+ kapasitas 10 HP untuk gedung besar. Mendukung hingga 18 indoor unit dengan pipa refrigerant panjang hingga 100 meter. Cocok untuk hotel, rumah sakit, dan perkantoran.',
        shortDesc: 'Daikin VRV IV+ 10 HP - Gedung Komersial',
        price: 165000000,
        originalPrice: 185000000,
        categoryId: catChiller.id,
        brand: 'Daikin',
        model: 'RXYQ10TAYJ',
        specifications: JSON.stringify({
          tipe: 'VRV IV+ (Outdoor Unit)',
          kapasitas: '10 HP (96.000 BTU/h)',
          refrigerant: 'R410A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '8.500 Watt',
          COP: '5.05',
          max_indoor_unit: '18 unit',
          jarak_pipa_maks: '100 meter (level sama)',
          fitur: ['Intelligent Touch Controller', 'BMS Integration', 'Night Purge', 'High Pressure Lift 50m'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'set',
      },
      {
        name: 'Samsung DVM S 5 PK',
        slug: 'samsung-dvm-s-5pk',
        description: 'Sistem VRF Samsung DVM S kapasitas 5 HP untuk gedung kecil hingga menengah. Teknologi Digital Inverter Boost untuk pendinginan cepat. Kontrol pintar via Samsung SmartThings.',
        shortDesc: 'Samsung DVM S 5 HP - Digital Inverter',
        price: 78000000,
        originalPrice: 88000000,
        categoryId: catChiller.id,
        brand: 'Samsung',
        model: 'AM060KN4DGH',
        specifications: JSON.stringify({
          tipe: 'VRF (Outdoor Unit)',
          kapasitas: '5 HP (48.000 BTU/h)',
          refrigerant: 'R410A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '4.500 Watt',
          COP: '4.65',
          max_indoor_unit: '9 unit',
          jarak_pipa_maks: '50 meter',
          fitur: ['Digital Inverter Boost', 'SmartThings Compatible', 'Auto Restart', 'Blackout Recovery'],
          garansi: '3 Tahun Kompressor, 1 Tahun Unit',
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'set',
      },
      {
        name: 'Cooling Tower 20 Ton - Industrial',
        slug: 'cooling-tower-20-ton-industrial',
        description: 'Cooling tower kapasitas 20 ton untuk sistem chiller water-cooled. Tipe forced draft dengan fill media PVC tahan panas. Konstruksi fiberglass FRP anti korosi. Cocok untuk pabrik, hotel, dan rumah sakit.',
        shortDesc: 'Cooling Tower 20 Ton FRP - Industrial',
        price: 65000000,
        originalPrice: 72000000,
        categoryId: catChiller.id,
        brand: 'Berkat Mandiri',
        model: 'CT-20T-FRP',
        specifications: JSON.stringify({
          tipe: 'Forced Draft Cooling Tower',
          kapasitas: '20 Ton Refrigeration',
          aliran_air: '10 m³/h',
          material_body: 'Fiberglass Reinforced Plastic (FRP)',
          fill_media: 'PVC',
          motor_fan: '2.2 kW',
          dimensi: '1.800 x 1.800 x 2.500 mm',
          berat: '450 kg',
          fitur: ['Anti Korosi', 'Low Noise Fan', 'Easy Maintenance', 'Chemical Dosing Port'],
          garansi: '2 Tahun',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
    ],
  })

  console.log(`📦 Created ${productsChiller.count} Chiller & VRV/VRF products`)

  // =====================
  // PRODUCTS - Mesin Pendingin
  // =====================
  const productsMesinPendingin = await db.product.createMany({
    data: [
      {
        name: 'Cold Room Panel 100mm - 1 Set (3x3x2.5m)',
        slug: 'cold-room-panel-100mm-3x3x2.5m',
        description: 'Panel cold room sandwich PU (Polyurethane) 100mm untuk ruang pendingin ukuran 3x3x2.5 meter. Suhu operasi -5°C hingga +10°C. Termasuk panel dinding, atap, lantai, dan pintu swing.',
        shortDesc: 'Panel Cold Room PU 100mm - 3x3x2.5m',
        price: 35000000,
        originalPrice: 40000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'CRP-100-3x3x2.5',
        specifications: JSON.stringify({
          tipe: 'Cold Room Panel Set',
          material_inti: 'Polyurethane (PU) 100mm',
          material_kulit: 'Pre-painted Steel 0.5mm',
          ukuran: '3 x 3 x 2.5 meter (P x L x T)',
          suhu_operasi: '-5°C ~ +10°C',
          include: ['Panel Dinding', 'Panel Atap', 'Panel Lantai', 'Pintu Swing', 'Karet Pintu', 'Heater Pintu'],
          warna: 'Putih',
          garansi: '5 Tahun Panel',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'set',
      },
      {
        name: 'Cooling Unit Cold Room 2 HP (Suhu -5°C s/d 10°C)',
        slug: 'cooling-unit-cold-room-2hp',
        description: 'Unit pendingin (cooling unit) untuk cold room kapasitas 2 HP. Tipe monoblok untuk kemudahan instalasi. Suhu operasi -5°C hingga +10°C cocok untuk penyimpanan sayuran, buah, dan produk segar.',
        shortDesc: 'Cooling Unit Cold Room 2 HP Monoblok',
        price: 22000000,
        originalPrice: 25000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'CU-2HP-MONO',
        specifications: JSON.stringify({
          tipe: 'Monoblok Cooling Unit',
          kapasitas: '2 HP (5.500 kcal/h)',
          refrigerant: 'R404A',
          tegangan: '220V / 1Phase / 50Hz',
          daya_listrik: '1.500 Watt',
          suhu_operasi: '-5°C ~ +10°C',
          evaporator: 'Copper Tube + Aluminium Fin',
          defrost: 'Electric Heater',
          thermostat: 'Digital',
          garansi: '1 Tahun',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Freezer Room Unit 5 HP (Suhu -25°C)',
        slug: 'freezer-room-unit-5hp',
        description: 'Unit pendingin untuk freezer room kapasitas 5 HP. Mampu mencapai suhu -25°C untuk penyimpanan produk beku. Tipe split dengan kondensor terpisah untuk efisiensi pendinginan maksimal.',
        shortDesc: 'Freezer Room Unit 5 HP - Suhu -25°C',
        price: 55000000,
        originalPrice: 62000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'FR-5HP-SPLIT',
        specifications: JSON.stringify({
          tipe: 'Split Freezer Unit',
          kapasitas: '5 HP (13.750 kcal/h)',
          refrigerant: 'R404A',
          tegangan: '380V / 3Phase / 50Hz',
          daya_listrik: '3.800 Watt',
          suhu_operasi: '-25°C ~ -18°C',
          evaporator: 'Copper Tube + Aluminium Fin (Defrost Electric)',
          kondensor: 'Air-Cooled Fin & Tube',
          thermostat: 'Digital with Defrost Timer',
          garansi: '1 Tahun',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Display Chiller 600L - Minuman',
        slug: 'display-chiller-600l-minuman',
        description: 'Display chiller kapasitas 600 liter untuk menampilkan dan menyimpan minuman. Suhu 2°C hingga 10°C dengan kaca tempered bening dan pencahayaan LED. Cocok untuk minimarket dan restoran.',
        shortDesc: 'Display Chiller 600L - Minuman & Minimarket',
        price: 18500000,
        originalPrice: 21000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'DC-600L',
        specifications: JSON.stringify({
          tipe: 'Display Chiller (Upright)',
          kapasitas: '600 Liter',
          suhu_operasi: '+2°C ~ +10°C',
          tegangan: '220V / 1Phase / 50Hz',
          daya_listrik: '450 Watt',
          refrigerant: 'R134a',
          rak: '5 tingkat (bisa diatur)',
          kaca: 'Tempered Glass 2 Lapis',
          pencahayaan: 'LED Interior',
          dimensi: '680 x 650 x 1950 mm',
          garansi: '1 Tahun Kompressor, 6 Bulan Unit',
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Ice Cube Machine 50 Kg/Hari',
        slug: 'ice-cube-machine-50kg-hari',
        description: 'Mesin pembuat es batu (ice cube) kapasitas 50 kg per hari. Es batu full cube ukuran standar 2x2x2 cm. Stainless steel AISI 304 food grade. Cocok untuk restoran, kafe, dan hotel.',
        shortDesc: 'Mesin Es Batu 50 Kg/Hari - Stainless Steel',
        price: 28000000,
        originalPrice: 32000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'ICM-50',
        specifications: JSON.stringify({
          tipe: 'Ice Cube Machine',
          kapasitas: '50 kg / 24 jam',
          ukuran_es: '22 x 22 x 22 mm (Full Cube)',
          tegangan: '220V / 1Phase / 50Hz',
          daya_listrik: '600 Watt',
          refrigerant: 'R404A',
          material: 'Stainless Steel AISI 304',
          siklus_produksi: '12-15 menit / batch',
          bin_kapasitas: '25 kg',
          berat: '65 kg',
          garansi: '1 Tahun Kompressor, 6 Bulan Unit',
        }),
        inStock: true,
        isFeatured: true,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Blast Chiller 30 Kg',
        slug: 'blast-chiller-30kg',
        description: 'Blast chiller kapasitas 30 kg untuk pendinginan cepat makanan. Dari suhu +90°C ke +3°C dalam 90 menit. Wajib untuk dapur hotel, restoran, dan katering yang memenuhi standar HACCP.',
        shortDesc: 'Blast Chiller 30 Kg - Standar HACCP',
        price: 45000000,
        originalPrice: 50000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'BC-30',
        specifications: JSON.stringify({
          tipe: 'Blast Chiller / Shock Freezer',
          kapasitas: '30 kg',
          pendinginan_cepat: '+90°C → +3°C dalam 90 menit',
          pembekuan_cepat: '+90°C → -18°C dalam 240 menit',
          tegangan: '220V / 1Phase / 50Hz',
          daya_listrik: '1.200 Watt',
          refrigerant: 'R404A',
          material: 'Stainless Steel AISI 304 Interior',
          kontrol: 'Digital Touch Screen',
          fitur: ['HACCP Compliant', 'Printer Port', 'USB Data Logger', 'Core Probe'],
          garansi: '1 Tahun',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Water Chiller 3 HP - Process Cooling',
        slug: 'water-chiller-3hp-process-cooling',
        description: 'Water chiller portabel kapasitas 3 HP untuk pendinginan proses industri. Suhu air keluar 5°C hingga 20°C. Tangki air built-in 50 liter dengan pompa sirkulasi. Cocok untuk mesin CNC, laser, dan injeksi plastik.',
        shortDesc: 'Water Chiller 3 HP - Industri & Proses',
        price: 38000000,
        originalPrice: 42000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'WC-3HP',
        specifications: JSON.stringify({
          tipe: 'Portable Water Chiller',
          kapasitas_pendinginan: '3 HP (8.250 kcal/h)',
          suhu_air_keluar: '+5°C ~ +20°C',
          tegangan: '220V / 1Phase / 50Hz',
          daya_listrik: '2.300 Watt',
          refrigerant: 'R410A',
          tangki_air: '50 Liter (Built-in)',
          pompa: 'Sirkulasi 30 L/min',
          kontrol: 'Digital Thermostat',
          fitur: ['Flow Switch', 'Overload Protection', 'Phase Reversal Relay'],
          dimensi: '850 x 500 x 900 mm',
          garansi: '1 Tahun',
        }),
        inStock: true,
        isFeatured: false,
        isNew: false,
        minOrder: 1,
        unit: 'unit',
      },
      {
        name: 'Walk-in Freezer Panel 150mm - 1 Set (4x3x2.5m)',
        slug: 'walk-in-freezer-panel-150mm-4x3x2.5m',
        description: 'Panel walk-in freezer sandwich PU 150mm untuk suhu rendah hingga -25°C. Ukuran 4x3x2.5 meter. Termasuk panel, pintu, dan heater. Cocok untuk gudang beku daging, ikan, dan es krim.',
        shortDesc: 'Walk-in Freezer Panel 150mm - 4x3x2.5m',
        price: 52000000,
        originalPrice: 58000000,
        categoryId: catMesinPendingin.id,
        brand: 'Berkat Mandiri',
        model: 'WFP-150-4x3x2.5',
        specifications: JSON.stringify({
          tipe: 'Walk-in Freezer Panel Set',
          material_inti: 'Polyurethane (PU) 150mm',
          material_kulit: 'Pre-painted Steel 0.6mm',
          ukuran: '4 x 3 x 2.5 meter (P x L x T)',
          suhu_operasi: '-25°C ~ -18°C',
          include: ['Panel Dinding', 'Panel Atap', 'Panel Lantai', 'Pintu Swing + Heater', 'Karet Pintu', 'Lampu LED'],
          warna: 'Putih',
          garansi: '5 Tahun Panel',
        }),
        inStock: true,
        isFeatured: false,
        isNew: true,
        minOrder: 1,
        unit: 'set',
      },
    ],
  })

  console.log(`📦 Created ${productsMesinPendingin.count} Mesin Pendingin products`)

  // =====================
  // TESTIMONIALS
  // =====================
  const testimonials = await db.testimonial.createMany({
    data: [
      {
        name: 'Budi Santoso',
        company: 'PT. Sinar Abadi Property',
        position: 'General Manager',
        content: 'Kami sudah bekerja sama dengan Berkat Mandiri Pendingin selama 3 tahun untuk proyek instalasi AC di gedung-gedung perkantoran kami. Kualitas produk dan pelayanan after-sales sangat memuaskan. Tim teknisi mereka responsif dan profesional. Harga juga sangat kompetitif dibandingkan supplier lain.',
        rating: 5,
        avatar: null,
        isApproved: true,
      },
      {
        name: 'Ir. Siti Rahayu',
        company: 'Hotel Permata Nusantara',
        position: 'Chief Engineer',
        content: 'Sistem VRV Daikin yang dipasang oleh Berkat Mandiri Pendingin berjalan sangat baik dan hemat energi. Dari 200 kamar hotel, suhu terjaga stabil sepanjang tahun. Support teknis 24/7 mereka sangat membantu ketika ada masalah di tengah malam. Sangat direkomendasikan!',
        rating: 5,
        avatar: null,
        isApproved: true,
      },
      {
        name: 'Ahmad Wijaya',
        company: 'CV. Mitra Sejahtera Abadi',
        position: 'Direktur',
        content: 'Kami membeli kompresor dan spare part AC secara rutin dari Berkat Mandiri Pendingin untuk bengkel service AC kami. Harga grosir sangat bersaing, stok selalu tersedia, dan pengiriman cepat ke bengkel kami di Tangerang. Terima kasih atas kerja samanya selama ini.',
        rating: 5,
        avatar: null,
        isApproved: true,
      },
      {
        name: 'Dewi Lestari',
        company: 'RS. Medika Utama',
        position: 'Dept. Head Fasilitas',
        content: 'Chiller dan cold room dari Berkat Mandiri Pendingin membantu rumah sakit kami menjaga standar penyimpanan obat dan vaksin. Instalasi rapi, tepat waktu, dan sesuai regulasi Kementerian Kesehatan. Kami sangat puas dengan kinerja mesin pendingin yang sudah beroperasi 2 tahun tanpa masalah.',
        rating: 4,
        avatar: null,
        isApproved: true,
      },
      {
        name: 'Hendra Kusuma',
        company: 'PT. Nusantara Food Industries',
        position: 'Plant Manager',
        content: 'Berkat Mandiri Pendingin menyediakan blast chiller dan cold room untuk pabrik makanan kami. Suhu terjaga dengan presisi, sangat penting untuk standar food safety. Tim mereka memahami kebutuhan industri makanan dan memberikan solusi yang tepat. Layanan terbaik!',
        rating: 5,
        avatar: null,
        isApproved: true,
      },
      {
        name: 'Rizky Pratama',
        company: 'Mall Ciputra Serpong',
        position: 'Building Manager',
        content: 'Sistem VRF 10 HP dari Berkat Mandiri Pendingin sudah beroperasi di area food court kami selama 1.5 tahun. Performa pendinginan excellent dan konsumsi listrik lebih rendah 25% dari sistem lama. Maintenance rutin dilakukan tepat waktu oleh tim mereka. Hubungan kerja sama yang sangat baik.',
        rating: 4,
        avatar: null,
        isApproved: true,
      },
      {
        name: 'Dr. Andi Susanto',
        company: 'Apotek K24 Cabang Bogor',
        position: 'Pemilik',
        content: 'Display chiller dan freezer dari Berkat Mandiri Pendingin sangat membantu apotek kami menyimpan obat-obatan yang membutuhkan suhu terkontrol. Harga terjangkau dan kualitas mesin tahan lama. Sudah 3 unit yang kami beli dan semuanya berjalan baik.',
        rating: 5,
        avatar: null,
        isApproved: true,
      },
    ],
  })

  console.log(`📦 Created ${testimonials.count} testimonials`)

  // Summary
  const totalProducts = productsAcSplit.count + productsKompresor.count + productsRefrigerant.count + productsSparePart.count + productsChiller.count + productsMesinPendingin.count
  console.log(`
============================================
✅ Seeding completed successfully!
============================================
Categories:     6
Products:       ${totalProducts}
  - AC Split:         ${productsAcSplit.count}
  - Kompresor:        ${productsKompresor.count}
  - Refrigerant:      ${productsRefrigerant.count}
  - Spare Part AC:    ${productsSparePart.count}
  - Chiller & VRV/VRF:${productsChiller.count}
  - Mesin Pendingin:  ${productsMesinPendingin.count}
Testimonials:   ${testimonials.count}
============================================
  `)
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
